### ISSUE TITLE
Found duplicate name errors in 4.17.0

### ISSUE THREAD

**Issue by viktornordling** [palantir/conjure#1005]
## What happened?
In 4.17.0 we released this PR: https://github.com/palantir/conjure/pull/948, which leads to `Found duplicate name` errors for normal, non-cyclic, imports.

E.g. we had:

file1.yml
```
types:
  definitions:
    default-package: com.palantir.some.package
    objects:
      MyType:
        fields:
          myField: string
```

file2.yml
```
types:
  conjure-imports:
    myImports: ./file1.yml
  definitions:
    default-package: com.palantir.some.other.package
    objects:
      MyOtherType:
        fields:
          myField: myImprts.MyType
```

And now we're getting `Found duplicate name` errors.
