### ISSUE TITLE
Allow optional alias as a header parameter

### ISSUE THREAD

**Issue by ferozco** [palantir/conjure#108]
@bavardage 	
I have a type which is an alias of a string

```yml
      MyTokenType:
        alias: string
```

and then I use it as a header parameter
```yml
    endpoints:
      myEndpoint:
        http: POST /
        args:
          someToken:
            param-id: My-Token
            param-type: header
            type: optional<MyTokenType>
          request: MyEndpointRequest
```

`Exception in thread "main" java.lang.IllegalStateException: Header parameters must be primitives, aliases or optional primitive: "temporaryCredentialsAuthToken" is not allowed`

I am able to switch the alias type to be itself `alias: optional<string>` (and take non-optional `MyTokenType` as the header param type) but I'm not sure the generated code then works (I haven't yet confirmed with a failing test) - `@JsonCreator` annotation ends up taking an `Optional<String>`
