### ISSUE TITLE
Circular package dependencies break certain languages

### ISSUE THREAD

**Issue by jdhenke** [palantir/conjure#131]
## What happened?

I created a valid conjure definition that introduced a cycle of package dependencies:

```yaml
types:
  definitions:
    objects:
      Type1:
        package: com.palantir.odd
        fields:
          type2: Type2
      Type2:
        package: com.palantir.even
        fields:
          type3: Type3
      Type3:
        package: com.palantir.odd
        fields: {}
services: {}
```

This is valid according to the spec, and the current conjure compiler successfully create an IR from this, however any straightforward bindings for a language like Go which forbids circular package dependencies would not be able to generate code that compiles for these definitions by using the packages as defined in conjure.

```
$ go build ./conjure/...
can't load package: import cycle not allowed
package internal-github/jhenke/bug-circular-conjure-imports/conjure/com/palantir/even
	imports internal-github/jhenke/bug-circular-conjure-imports/conjure/com/palantir/odd
	imports internal-github/jhenke/bug-circular-conjure-imports/conjure/com/palantir/even
import cycle not allowed
package internal-github/jhenke/bug-circular-conjure-imports/conjure/com/palantir/even
	imports internal-github/jhenke/bug-circular-conjure-imports/conjure/com/palantir/odd
	imports internal-github/jhenke/bug-circular-conjure-imports/conjure/com/palantir/even
```

## What did you want to happen?

I want there to be a recommendation on how languages which do not support circular dependencies should handle this situation or a change in the conjure spec and compiler to forbid this behavior.
