### ISSUE TITLE
map<any, T> shouldn't be allowed

### ISSUE THREAD

**Issue by iamdanfox** [palantir/conjure#135]
## What happened?

I was able to write a conjure definition which seems to be non-representable in JSON.  Here's a spec-test that passes but I think it shouldn't pass:

```yml
  aliasOfMapKeyAnyNotAllowed:
    expected-error: 'TODO'
    conjure:
      types:
        definitions:
          default-package: test.api
          objects:
            MapAnyAliasExample:
              alias: map<any, boolean>
  objectFieldWithMapKeyAnyNotAllowed:
    expected-error: 'TODO'
    conjure:
      types:
        definitions:
          default-package: test.api
          objects:
            MapAnyObjectExample:
              fields:
                bad: map<any, boolean>
  objectWithAliasOfMapKeyAnyNotAllowed:
    expected-error: 'TODO'
    conjure:
      types:
        definitions:
          default-package: test.api
          objects:
            MapAnyAliasExample:
              alias: map<any, boolean>
            MapAnyObjectExample:
              fields:
                bad: MapAnyAliasExample
```
## What did you want to happen?

A nice validation message explaining why this is not allowed.

Also I think the source_files specification should probably describe this limitation: https://github.com/palantir/conjure/blob/develop/docs/spec/source_files.md#containertype

## Proposal

In order to implement this, I think we'll need to use the DealiasingTypeVisitor but currently validation happens as objects are constructed, before the entire definition is created.
