### ISSUE TITLE
`type` should be forbidden as a union variant name

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure#179]
This definition passes validation and generates code with the conjure-java backend, but can't possibly work:

```yaml
types:
  definitions:
    objects:
      union:
        type: string
```

It should be forbidden by the conjure parser.
