### ISSUE TITLE
More Flexible AuthDefinition

### ISSUE THREAD

**Issue by shzhng** [palantir/conjure#217]
## Motivation

We use [DropWizard Auth](https://www.dropwizard.io/1.0.0/docs/manual/auth.html), which is unsupported by `default-auth` or `auth` definitions for services.

ideally there should be someway to generate a service with such a method

```java
@Path("/this/is/a/path")
@POST
SomeResponse getSomeSecret(@Auth UserPrincipal principal, SomeRequest request);
```

## Proposal
make the `header` option more configurable, perhaps something like so:

```yaml
header:
  type: UserPrincipal
  markers:
    - Auth
  param-id: Authorization # the default
```

**Comment by iamdanfox** [comment]
@shzhng how would you want a typescript or python client to interact with an API that has a rich 'UserPrincipal' type?

```yaml
default-auth:
  header:
    type: UserPrincipal
    markers:
      - Auth
    param-id: Authorization
```

**Comment by shzhng** [comment]
so i'd imagine on client side it wouldn't change from the current behavior, which is just setting the `'Authorization': 'Bearer {TOKEN}'` header?

**Comment by uschi2000** [comment]
@shzhng , the conjure language primarily describes the wire format of RPC messages and as such is likely not the right place for the feature you desire. It would make more sense as a flag to the conjure-jaxrs generator, but I suspect that there are a few problems to work through, e.g., the difference between client-side and server-side code gen.

**Comment by shzhng** [comment]
@uschi2000 understood and agreed. I supposed, given that i'm able to sorta hackily generate what i want by doing the following

```yaml
getSomeSecret:
  http: GET /this/is/a/path
  args:
    principal:
      param-type: header
      param-id: Authorization
      type: UserPrincipal
      markers:
        - Auth
```

albeit in a really cumbersome manner on every single endpoint (and also generating the unnecessary `@HeaderParam("Authorization")` , that this might be something that's possible to define on the wire format
