### ISSUE TITLE
Allow Unit type at least for Union Types

### ISSUE THREAD

**Issue by gm2211** [palantir/conjure#243]
## What happened?

**BLUF**: Some times the name of the union type in the union delivers enough information in itself and it should have type void (or Unit type).

**NOTE**: This is part of a pattern in which union types are used as enums but where some of the enum values should have additional info while others don't need to.

Example:

Gonna take a long-winded approach here
Let's say I have a batch endpoint to get results for jobs - there are a few ways to model this:

```
// throws if insufficient permissions or any error for any
map<jobId, result> compute(...)
```
or
```
// return partial map if insufficient permissions or any error for any
map<jobId, result> compute(...)
```
or
```
// make result a union type that includes individual error states
map<jobId, result> compute(...)
```

Out of the 3 options, I would argue the latter gives us the most flexibility while at the same time forcing the client to make decisions about what to do for failures (while the partial map approach wouldn't).

This leads me to the actual issue at hand: how do we model the result union type to include error states. Here's one way

```
Result:
  union:
     insufficientPermissions: <WHAT_HERE>
     invalidRequest: SerializableError
     result: ResultWithMetrics
```

Now I can see 3 options that are currently available to replace `<WHAT_HERE>`:

1. Create an object with extra info about the insufficient permissions error
2. Use `string` and always pass an empty string
3. Create "singleton" enum like this:
```
InsufficientPermissions:
  values:
    - INSTANCE
```

Option 1. could work in this case, but there are some cases in which there really isn't much info to be provided at all.
Option 2. is pretty confusing because if I see a string I expect it to contain something
Option 3. is pretty verbose:
```
Result.insufficientPermissions(InsufficientPermissions.INSTANCE);
```

## What did you want to happen?
I would like to be able to do this:

```
Result:
  union:
     insufficientPermissions: unit # or 'void'
     invalidRequest: SerializableError
     result: ResultWithMetrics
```

and 

```
Result.insufficientPermissions();
```
