### ISSUE TITLE
Routing for ambiguous service endpoints is not specified

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure#305]
Consider the following (legal) Conjure definition:

```yml
services:
  FooService:
    name: FooService
    package: com.palantir.conjure
    base-path: /foo
    endpoints:
      first:
        http: GET /foo/{param}
        args:
          param: string
      second:
        http: GET /{param}/foo
        args:
          param: string
```

What is the expected behavior if I make an HTTP request to `/foo/foo/foo`? That matches both endpoint definitions.
