### ISSUE TITLE
Generated Typescript incorrect when referencing an alias of a map

### ISSUE THREAD

**Issue by rherms** [palantir/conjure#314]
## What happened?

The generated typescript code would not compile because of a missing import. Here is a simplification of my conjure:

```
Foo:
  fields:
    myField: Bar

Bar:
  alias: map<string, Baz>

Baz:
  union:
    str: string
    date: datetime
```

The generated code for `Foo.ts` did not import `IBaz` even though it referenced it. It looked something like:
```
export interface IFoo {
  myField: { [key: string]: IBaz };
}
```

## What did you want to happen?
Valid typescript to be generated, like:
```
import { IBaz } from "./Baz";

export interface IFoo {
  myField: { [key: string]: IBaz };
}
```
