### ISSUE TITLE
Invalid HTTP methods are allowed

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure#417]
Conjure successfully builds IR for endpoints with a bogus HTTP method:

```yaml
services:
  FooService:
    endpoints:
      what:
        http: FOO /bar
```
