### ISSUE TITLE
Conjure generator accepts invalid query parameter types

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure#491]
## What happened?
Ran the Conjure generator on the following definition, and it succeeded/generated IR without any errors:

```yml
services:
  TestService:
    name: Test Service
    package: api
    endpoints:
      queryParamListBinary:
        http: GET /binaryListQueryVar
        args:
          myQueryParam1:
            type: list<binary>
            param-type: query
```

## What did you want to happen?
CLI should report that the definition is invalid/illegal and fail, as, per the [Conjure definition document](https://github.com/palantir/conjure/blob/master/docs/spec/conjure_definitions.md#argumentdefinition), query parameters cannot be binary (or a container of it):

> If the param-type is query then the de-aliased type MUST be an enum or a primitive (except binary and bearertoken), or a container (list, set, optional) of one of these.
