### ISSUE TITLE
Proposal: concise markers

### ISSUE THREAD

**Issue by markelliot** [palantir/conjure#56]
Our syntax for markers is pretty verbose, which makes large APIs with lots of safe arguments (marked with an appropriate `Safe` type) very verbose and a little hard to read. I think we should strive to make things both readable and concise. I'd like to propose we explore ways to make markers more concise.

As an example, today:

```yaml
getFoo:
  http: GET /{foo}
  args:
    foo:
      type: string
      markers:
        - Safe
```

I think it'd be good if we could make this more concise, and allow types to carry marker information, e.g.:

```yaml
getFoo:
  http: GET /{foo}
  args:
    foo:
      type: @Safe string
```

If using arg shorthand, this can actually collapse to:

```yaml
getFoo:
  http: GET /{foo}
  args:
    foo: @Safe string
```

More concretely, I'd propose that one can use `@<Type>` as a marker anywhere `type` is allowed, and that we'd parse this as a marker on the item. The `@` syntax follows most language definitions for annotations, and we use markers as an indication of meta information much the same way most languages use annotations, so the correspondence seems friendly.

To add precision, something like:

```
MARKER := "@"TYPE
MARKED_TYPE := (MARKER )*TYPE
```

And replacing `TYPE` with `MARKED_TYPE` wherever markers are allowed.
