### ISSUE TITLE
Alias of string should be allowed in path parameters

### ISSUE THREAD

**Issue by iamdanfox** [palantir/conjure#61]
Currently, it seems that conjure disallows aliases of strings as path parameters: `Path parameters must be primitives or aliases: "foo" is not allowed`

```yaml
type:
  definitions:
    default-package: package.example
    objects:
      StringAlias:
        alias: string
services:
  ExampleService:
  ...
  endpoints:
    endpoint:
      http: POST /{foo}
      args:
        foo: StringAlias
```
