### ISSUE TITLE
Deprecating an entire object

### ISSUE THREAD

**Issue by felixdesouza** [palantir/conjure#617]
## Motivation
We have deprecation of fields, enums and endpoints. It feels like a natural extension to deprecate entire objects that shouldn't be used anymore. Can we extend the deprecation syntax to objects too?

## Proposal
That is:
```yaml
Metadata:
  deprecated: Use MetadataV2 instead etc.
  docs: Bla
  fields: 
    field1: string
    field2: string
```

Could go even further and add deprecation notices to the methods of deprecated objects, I don't think it comes up otherwise. But at the very least it'd be nice to have it baked in similar to fields, enums and endpoints.

I can throw something up if it's a reasonable proposal?
