### ISSUE TITLE
Disallow implicit/explicit null in place of empty map in source files

### ISSUE THREAD

**Issue by tdeitch** [palantir/conjure#82]
Right now the following are all parsed equivalently:

```
MyType:
  fields:
  docs: Some documentation about the whole type
  package: com.palantir.example
```
```
MyType:
  fields: null
  docs: Some documentation about the whole type
  package: com.palantir.example
```
```
MyType:
  fields: {}
  docs: Some documentation about the whole type
  package: com.palantir.example
```

The source files spec says that `fields` should be a map. We coerce `null` to an empty collection when deserializing from the wire format, which is fine, but we should keep them distinct in the source files. Therefore, the first two examples here should not be treated as valid Conjure and the parser should reject them.
