### ISSUE TITLE
Handle Generics of external type OR Allow Conjure-created object to inherit an external object

### ISSUE THREAD

**Issue by gbouv** [palantir/conjure#84]
Hey Conjure team!

We are trying to move our services to Conjure to "normalize" our code, and I hit the situation recently. I could not find any work-around.

I want my service to return paginated results. The return objects should have the following structure:
```
public interface PaginatedResult<R> {
    R getResult();
    Optional<String> getPageToken();
}
```
For some reasons, I have the `PaginatedResult` object above already implemented in an external library. Ideally, I would like my conjure config to look like: 
```
types:
  imports:
    PaginatedResult:
      external:
        java: com.palantir...........PaginatedResult
definitions:
    default-package: com.palantir.....
    objects:
      MyResponseObject:
        fields:
          name: string
          otherField: string
service:
  MyService:
    name: MyServiceName
    package: com.palantir.......
    default-auth: header
    endpoints:
      myEndpoint:
        http: POST /endpoint
        args:
          request:
            type: string
        returns: PaginatedResult<MyResponseObject>
```
The problem is that it seems like Generics for external types are not handled yet. Am I correct?

A work-around for this would be to be able for conjure created object to inherit an external type. This way, I could make `MyResponseObject` inherit a `PaginatedResult` object that would contain only the page token, and it would be fine (but I find it less elegant). But still, this can not be done neither if I am not mistaken.

The only working solution I found is by defining two object in my `conjure.yml` file. The original `MyResponseObject` plus a `MyResponseObjectPaginated` that is basically a wrapper around the first object to add the page token. But there are some drawbacks with that:
1. We want to implement this "pagination" mechanism in a bunch of services and it means that we will always have to create twice a much objects.
2. More importantly, in the actual code, I actually get my `PaginatedResult` object from a call to an external library (not the service itself). Which means that ATM, I have to: 1. call my library which returns my PaginatedObject 2. unwrap it 3. construct the `MyResponseObjectPaginated` from the unwrapped object 4. returns this object. This could be done by a single call to my external library if generics were handled.

I hope it was clear enough. My questions are:
- Do you have a way to handle that kind of situation? (maybe I missed some features)
- If not, are there some FR on the short-term roadmap that will solve this?
