### ISSUE TITLE
Spec for query parameters does not match behavior of IR compiler

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure#92]
BLUF: Conjure spec states that header and query parameters can only be primitives or optional of primitives. However, the IR generator allows `list<string>` query parameters (but not header parameters). The spec or generator should be updated so they are in agreement on behavior.

--------

In the https://github.com/palantir/conjure/blob/develop/docs/spec/source_files.md#argumentdefinition section of the spec, the documentation for the `type` field states:

>  The type MUST be a primitive if the argument is a path parameter and primitive or optional of primitive if the argument is header or query parameter.

This seems to be enforced for header parameters, as specifying `list<string>` as a type fails:

```
services:
  TestService:
    name: Test Service
    package: com.palantir.another
    endpoints:
      headerParam:
        http: GET /headerParam
        args:
          foo:
            param-type: header
            param-id: FOO
            type: list<string>
```

Fails with:

```
Exception in thread "main" java.lang.IllegalStateException: Header parameters must be primitives, aliases or optional primitive: "foo" is not allowed
```

However, it is possible to generate query parameters that are collection types.

The input:

```
services:
  TestService:
    name: Test Service
    package: com.palantir.another
    endpoints:
      headerParam:
        http: GET /headerParam
        args:
          foo:
            param-type: query
            type: list<string>
```

Produces the IR:

```
{
  "version" : 1,
  "errors" : [ ],
  "types" : [ ],
  "services" : [ {
    "serviceName" : {
      "name" : "TestService",
      "package" : "com.palantir.another"
    },
    "endpoints" : [ {
      "endpointName" : "headerParam",
      "httpMethod" : "GET",
      "httpPath" : "/headerParam",
      "args" : [ {
        "argName" : "foo",
        "type" : {
          "type" : "list",
          "list" : {
            "itemType" : {
              "type" : "primitive",
              "primitive" : "STRING"
            }
          }
        },
        "paramType" : {
          "type" : "query",
          "query" : {
            "paramId" : "foo"
          }
        },
        "markers" : [ ]
      } ],
      "markers" : [ ]
    } ]
  } ]
}
```

This does not match what is outlined in the spec -- the spec should be updated or the implementation should be changed to match it.
