### ISSUE TITLE
conjure-imports name can't be setxxx, mapxxx ....

### ISSUE THREAD

**Issue by wenhoujx** [palantir/conjure#952]
## What happened?
conjure doesn’t like this b/c it thinks setting  starts a set ….

```
types:
  conjure-imports:
    setting: .....yml

      GetSomethingResponse:
        fields:
          settings: map<common.TeamRid, setting.CentralProductSetting>
```

it throws token at the place expects start object token .
